language: java
jdk:
- oraclejdk8
sudo: required

branches:
only: develop

before_script:
  - wget http://services.gradle.org/distributions/gradle-4.7-bin.zip
  - unzip gradle-4.7-bin.zip
  - export GRADLE_HOME=$PWD/gradle-4.7
  - export PATH=$GRADLE_HOME/bin:$PATH

script:
- gradle test
- gradle check

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
